import toml

# Load the configuration from the TOML file
config = toml.load("config.toml")

# Access the API key
OPENAI_API_KEY= config["openai"]["OPENAI_API_KEY"]

# Use the API key in your application
